### ISSUE TITLE
Broken Quest

### ISSUE THREAD

**Issue by LABSTORM-MG** [AllTheMods/ATM-8#1648]
The quest "The Fission Reactor Interface" won't detect that I have completed it.

![grafik](https://github.com/AllTheMods/ATM-8/assets/94696488/d1e1b26e-23a2-49f2-8c22-0e5ad2b08098)
![grafik](https://github.com/AllTheMods/ATM-8/assets/94696488/8c80e251-1a2c-430f-ab58-1fe53f034981)

But every time I look at my Mekanism Fission Reactor or my Mekanism Turbine, the server console gets spammed with these issues.

``` bash
#4: Error occurred while handling event 'NetworkEvents.dataReceived': ReferenceError: "FTBQuests" is not defined. (server_scripts:mods/ftbquests/customTask.js#4)
#4: Error occurred while handling event 'NetworkEvents.dataReceived': ReferenceError: "FTBQuests" is not defined. (server_scripts:mods/ftbquests/customTask.js#4)
#4: Error occurred while handling event 'NetworkEvents.dataReceived': ReferenceError: "FTBQuests" is not defined. (server_scripts:mods/ftbquests/customTask.js#4)
```

This is happening since I updated the server from ATM 1.0.22 to 1.0.23.
Is this happening because I did the update wrong and is there any way to fix this or skip the quest?

**Comment by zebau** [comment]
This also occurs even if the quest is already complete. I already have the quest and my console gets spammed with the same error if I look at the fission or sps reactor

**Comment by billylombardy** [comment]
Since ATM8 1.0.23 my server console keeps sending errors saying the same thing
Few minutes later i got to check FTBQuests version installed in the modpack
At this time, the version used is "1902.5.3-build.258"

So I went to FTBQuests's CurseForge saw this warning in the first lines
```
"Warning
As of FTB Quests 1902.5.0 you will need to use [FTB XMod Compat](https://legacy.curseforge.com/minecraft/mc-mods/ftb-xmod-compat) if you want to have KubeJS, JEI, REI or Game stages integration with FTB Quests."
```

I think the mod FTB XMod Compat is missing in the modpack
So KubeJS crashes when it tries to plug with FTBQuests
I don't have time to fix this on my own with a pull request
So if I'm not wrong, can someone fix it ?

**Comment by Mitchell5200** [comment]
We will be adding that "Xmod compat" for FTB quests next update, that should fix this issue.

**Comment by RisingDark512** [comment]
So this "broken quest" report is closed since Oct, 16 2023 but now in ATM 9  in 10/2024 this quest for observing a completed fission reactor is not claimable for me. I tried it several times by using different reactorsizes, from smallest to largest and getting them running every time, but still not claimable. If my english is bad I´m sorry, my mainlanguage is german haha. Maybe I´ll get help from someone even more than a year after this report was closed. If you need more informations just tell me and I´ll try my best to hand them to you. Thanks already :))

**Comment by WTFRichard** [comment]
Also having the same issue with the "observe completed fission reactor" quest. Unclaimable and does not complete even though I have access to the interface and have tried a couple different configurations.
